### ISSUE TITLE
getBug() returns a generic "HTTP status 400" for non-public bugs

### ISSUE THREAD

**Issue by edmorley** [canuckistani/bz.js#17]
https://api-dev.bugzilla.mozilla.org/latest/bug/767101 returns:
```
code: 102
error: 1
message: Access Denied
```

However bz.js' getBug() doesn't attempt to parse the response, since the response status is 400:
```
    else if(response.status >= 300 || response.status < 200)
      error = "HTTP status " + response.status;
    else {
      try {
        json = JSON.parse(response.responseText);
      } catch(e) {
        error = "Response wasn't valid json: '" + response.responseText + "'";         
      }
    }
```

So we lose the "Access Denied" message, and instead return an err value of "HTTP status 400", which presumably can occur for other malformed request cases too.

This means that in the case of https://github.com/harthur/bugzilla-todos/issues/55 we have to treat HTTP 400s as all being access denied, when it would be useful to surface the other cases differently.

**Comment by canuckistani** [comment]
@edmorley this should be fixed with the adoption of the REST api. I noticed you referenced a bugmotodo bug here, I have not yet taken a look at that code to see if it needs to be adjusted for this new verison of bz.js - hang tight.

**Comment by edmorley** [comment]
The issue in question 404s now, the new URL is https://github.com/fitzgen/bugzilla-todos/issues/55
