### ISSUE TITLE
Native REST api doesn't have /configuration

### ISSUE THREAD

**Issue by KWierso** [canuckistani/bz.js#27]
Need to use the URL described in https://bugzilla.mozilla.org/show_bug.cgi?id=924405#c11 until DKL adds an equivalent.

**Comment by KWierso** [comment]
Hrm, requesting https://bugzilla.mozilla.org/config.cgi?ctype=json directly gets blocked by CORS...

**Comment by KWierso** [comment]
Hopefully bug 1157993 gets fixed soonish :)

**Comment by canuckistani** [comment]
This is resolved in 5b3c6c5
