### ISSUE TITLE
provide api to product REST API - /rest/product

### ISSUE THREAD

**Issue by coyotebringsfire** [canuckistani/bz.js#32]
I'm working on a project to make a yeoman generator to file bug reports in bugzilla, and I need to get product information from bugzilla so I can auto fill fields like product, component and version. I've implemented the code in my own project to query and process the /rest/product API. Would you consider a PR which adds methods to the BugzillaClient class to get this product information?

**Comment by canuckistani** [comment]
Yes.

**Comment by canuckistani** [comment]
So here's the thing - you've only changed the built files, eg build/node/index.js, whereas to make changes what you really need to do is edit src/index.js and then run gulp to build the new files.

Also, src/index.js is written using ES6 syntax, which allows you to use es6 promises - there should be no need to include / use the Q library.

**Comment by coyotebringsfire** [comment]
I've refactored my PR so they are in src/index.js and also use native Promises. I closed the original PR and opened a new one https://github.com/canuckistani/bz.js/pull/34
